name: Release artifacts
on:
#  Will run when a comment is added in PR e.g. /release v0.6.40-0.1.0-beta.1
  issue_comment:
    types: [ created ]
  workflow_dispatch:

jobs:
  publish-artifacts:
    if: contains(github.event.comment.html_url, '/pull') && startsWith(github.event.comment.body, '/release v')
    runs-on: ubuntu-20.04
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.PUBLIC_DOCKER_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKER_PASSWORD }}

      - name: Set ENV variable
        env:
          RELEASE_VERSION_COMMENT: ${{ github.event.comment.body }}
        run: |
          echo "VERSION=${RELEASE_VERSION_COMMENT##/release\ v}" >> $GITHUB_ENV
          echo "Setting tag version: ${VERSION}"

      - name: Build with Gradle
        uses: hypertrace/github-actions/gradle@main
        with:
          args: build dockerBuildImages
        env:
          DOCKER_USERNAME: ${{ secrets.PUBLIC_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.PUBLIC_DOCKER_PASSWORD }}
          IMAGE_TAG: ${{ env.VERSION }}

      - name: push docker image
        uses: hypertrace/github-actions/gradle@main
        with:
          args: dockerPushImages
        env:
          DOCKER_USERNAME: ${{ secrets.PUBLIC_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.PUBLIC_DOCKER_PASSWORD }}
          IMAGE_TAG: ${{ env.VERSION }}