name: Release artifacts
on:
  # Will only run when release is published.
  issue_comment:
    types: [ created ]
  workflow_dispatch:

jobs:
  publish-artifacts:
    runs-on: ubuntu-20.04
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.PUBLIC_DOCKER_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKER_PASSWORD }}

      - name: Set env. variable
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: hypertrace/hypertrace-ingester:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}
            GIT_COMMIT=${GITHUB_SHA}